name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider:
  http: ^0.12.0+4
  audioplayer: ^0.5.2
  font_awesome_flutter: "any"
  pinput: ^0.1.10
  carousel_slider: ^1.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/OpenSans-Bold.ttf

      - family: CutsomIcons
        fonts:
          - asset: assets/fonts/CutsomIcons.ttf
          
      
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-ExtraLight.ttf
            weight: 100
          - asset: assets/fonts/Poppins-Thin.ttf
            weight: 200
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300          
          - asset: assets/fonts/Poppins-Regular.ttf          
            weight: 400
          - asset: assets/fonts/Poppins-Medium.ttf          
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf          
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          - asset: assets/fonts/Poppins-Black.ttf
            weight: 800
          - asset: assets/fonts/Poppins-ExtraBold.ttf
            weight: 900       
      
          
  assets:
    - assets/GenresImages/
    - assets/AlbumImages/
    - logo.png
    - background.png
    - BG.jpg
    - music_circle.png
    - circle.png
    - slogan.png
    - qshape.png
    - FP1.png
    - assets/drawable-xxxhdpi/rp2.png
    - assets/drawable-xxxhdpi/rp3.png
    - assets/drawable-xxxhdpi/83957883-cartoon-vector-doodles-music-illustration.png

    
