name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider:
  http: ^0.12.0+4
  audioplayer: ^0.5.2
  font_awesome_flutter: "any"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/OpenSans-Bold.ttf
  assets:
    - logo.png
    - background.png
    - BG.jpg
    - music_circle.png
    - circle.png
    - slogan.png
