name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider:
  http: ^0.12.0+4
  audioplayer: ^0.5.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true